version: "3"
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: kore.sh
    container_name: mail
    networks:
            - kore-ldap
            - kore-mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
      - /storage/kore/mail-storage:/var/mail
      - /storage/kore/mail-state:/var/mail-state
      - /storage/kore/mail-config:/tmp/docker-mailserver/
    environment:
    - DMS_DEBUG=0
    - ENABLE_CLAMAV=0
    - ONE_DIR=0
    - ENABLE_POP3=
    - ENABLE_FAIL2BAN=0
    - ENABLE_MANAGESIEVE=0
    - OVERRIDE_HOSTNAME=kore.sh
    - POSTMASTER_ADDRESS=postmaster@kore.sh
    - POSTSCREEN_ACTION=enforce
    - REPORT_RECIPIENT=0
    - REPORT_SENDER=
    - REPORT_INTERVAL=daily
    - SMTP_ONLY=
    - SSL_TYPE=
    - TLS_LEVEL=
    - SPOOF_PROTECTION=
    - ENABLE_SRS=0
    - PERMIT_DOCKER=network
    - VIRUSMAILS_DELETE_DELAY=
    - ENABLE_POSTFIX_VIRTUAL_TRANSPORT=
    - POSTFIX_DAGENT=
    - POSTFIX_MAILBOX_SIZE_LIMIT=
    - POSTFIX_MESSAGE_SIZE_LIMIT=
    - ENABLE_SPAMASSASSIN=1
    - SA_TAG=2.0
    - SA_TAG2=6.31
    - SA_KILL=6.31
    - SA_SPAM_SUBJECT=***SPAM*****
    - ENABLE_FETCHMAIL=0
    - FETCHMAIL_POLL=300
    - ENABLE_LDAP=1
    - LDAP_START_TLS=
    - LDAP_SERVER_HOST=kore-ldap-openldap
    - LDAP_SEARCH_BASE=ou=users,dc=kore,dc=sh
    - LDAP_BIND_DN=cn=admin,dc=kore,dc=sh
    - LDAP_BIND_PW=dcfvgbhn
    - LDAP_QUERY_FILTER_USER=(&(mail=%s)(mailenable=TRUE))
    - LDAP_QUERY_FILTER_GROUP=(&(mailGroupMember=%s)(mailenable=TRUE))
    - LDAP_QUERY_FILTER_ALIAS=(&(mailAlias=%s)(mailenable=TRUE))
    - LDAP_QUERY_FILTER_DOMAIN=(&(|(mail=*@%s)(mailalias=*@%s)(mailGroupMember=*@%s))(mailenable=TRUE))
    - DOVECOT_TLS=
    - DOVECOT_USER_FILTER=(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))
    - DOVECOT_PASS_FILTER=(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))
    - ENABLE_POSTGREY=0
    - POSTGREY_DELAY=300
    - POSTGREY_MAX_AGE=35
    - POSTGREY_AUTO_WHITELIST_CLIENTS=5
    - POSTGREY_TEXT=Delayed
    - ENABLE_SASLAUTHD=0
    - SASLAUTHD_MECHANISMS=
    - SASLAUTHD_MECH_OPTIONS=
    - SASLAUTHD_LDAP_SERVER=
    - SASLAUTHD_LDAP_SSL=
    - SASLAUTHD_LDAP_BIND_DN=
    - SASLAUTHD_LDAP_PASSWORD=
    - SASLAUTHD_LDAP_SEARCH_BASE=
    - SASLAUTHD_LDAP_FILTER=
    - SASLAUTHD_LDAP_START_TLS=
    - SASLAUTHD_LDAP_TLS_CHECK_PEER=
    - SASL_PASSWD=
    - SRS_EXCLUDE_DOMAINS=
    - SRS_SECRET=
    - DEFAULT_RELAY_HOST=
    - RELAY_HOST=
    - RELAY_PORT=25
    - RELAY_USER=
    - RELAY_PASSWORD=
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
  sogo:
    image: jenserat/sogo
    networks:
            - kore-ldap
            - kore-mail
            - kore-web
            - sogo
    volumes:
      - /storage/kore/sogo-data/:/srv
    deploy:
      labels:
        - traefik.docker.network=kore-web
        - traefik.enable=true
        - traefik.frontend.rule=Host:mail.kore.sh
        - traefik.port=80
  sogodb:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=sogo
      - POSTGRES_USER=sogo
      - POSTGRES_DB=sogo
    networks:
            - sogo
networks:
        sogo:
        kore-mail:
                external:
                        name: kore-mail
        kore-ldap:
                external:
                        name: kore-ldap
        kore-web:
                external:
                        name: kore-web